version: 0.0
os: linux
files:
  - source: /build
    destination: /home/ubuntu/shell
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
