version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/shell
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      timeout: 300
