version: '3'

services: 
    job-redis-queue:
        container_name: 'job-redis-queue'
        image: 'redis'
        ports: 
            - "6379:6379"

    archive-server:
        container_name: 'archive-server'
        build : .
        ports: 
            - "3003:3003"
        env_file: .env
        environment: 
            APP_VERSION: $APP_VERSION,
            SEARCH_HOST: $SEARCH_HOST,
            SEARCH_PORT: $SEARCH_PORT,
            SQL_DB_HOST: $SQL_DB_HOST,
            SQL_DB_PASSWORD: $SQL_DB_PASSWORD
            SQL_DB_PORT: $SQL_DB_PORT
            SQL_DB_USERNAME: $SQL_DB_USERNAME
            SQL_TABLE_NAME: $SQL_TABLE_NAME
            TATTLE_UI_AWS_ACCESS_KEY: $TATTLE_UI_AWS_ACCESS_KEY
            TATTLE_UI_AWS_SECRET_ACCESS_KEY: $TATTLE_UI_AWS_SECRET_ACCESS_KEY
        depends_on: 
            - job-redis-queue