name: update-public-registry

on: 
  push:
    branches: 
      - registry

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        ref: registry
      
    - name: Publish to Docker2
      uses: dennyabrain/docker-action@master
      with:
        username: tattletech
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tattletech/archive-server
        tag: latest
        arg1: ${{ secrets.AWS_ACCESS_KEY_ID }}
        arg2: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
